### ISSUE TITLE
knife zero bootstrap broken by knife rehash

### ISSUE THREAD

**Issue by btm** [higanworks/knife-zero#70] opened 2015-11-23 16:46 UTC
reported by @epcim on chef/chef gitter.

```
$ time knife null
45.08user 0.34system 0:47.51elapsed 95%CPU (0avgtext+0avgdata 94428maxresident)k
0inputs+0outputs (0major+26612minor)pagefaults 0swaps

$ knife rehash
Using knife-rehash will speed up knife's load time by caching the location of subcommands on disk.
However, you will need to update the cache by running `knife rehash` anytime you install a new knife plugin.
Knife subcommands are cached in /home/pmichalec/.chef/plugin_manifest.json. Delete this file to disable the caching.

$ time knife null
0.46user 0.07system 0:02.54elapsed 21%CPU (0avgtext+0avgdata 37380maxresident)k
0inputs+0outputs (0major+12306minor)pagefaults 0swaps
so far all good, but some thins stopped to work:

$ knife zero
FATAL: Cannot find subcommand for: 'zero'
If this is a recently installed plugin, please run 'knife rehash' to update the subcommands cache.
Available zero subcommands: (for details, knife SUB-COMMAND --help)

** ZERO COMMANDS **
knife zero bootstrap FQDN (options)
knife zero chef_client QUERY (options) | It's same as converge
knife zero converge QUERY (options)
knife zero diagnose # show configuration from file

[10] $ knife zero bootstrap
/home/pmichalec/.chefdk/gem/ruby/2.1.0/gems/knife-zero-1.10.0/lib/chef/knife/zero_base.rb:11:in `block (2 levels) in included': uninitialized constant Chef::Knife::Ssh (NameError)
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:216:in `call'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:216:in `block in load_deps'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:215:in `each'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:215:in `load_deps'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:200:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
    from /opt/chefdk/bin/knife:54:in `load'
    from /opt/chefdk/bin/knife:54:in `<main>'
```

Adding `require 'chef/knife/ssh'` to `lib/chef/knife/zero_base.rb` appears to fix this. I haven't dug deep enough to tell if this correct given the refactoring around `knife rehash` but I would guess load the `plugin_manifest.json` from `knife rehash` happens to produce a different load order. Maybe @stevendanna knows off the top of his head if this theory is correct.

**Comment by stevendanna** [comment] 2015-11-23 17:03
@btm If zero_base.rb requires Knife:SSH it should require it.  Adding the require is the correct fix.

**Comment by stevendanna** [comment] 2015-11-23 17:04
However, the zero_base.rb thing makes me worry that we might not be connecting the correct file because of the class structure of that plugin.

**Comment by sawanoboly** [comment] 2015-11-24 02:22
Thank you for report :smile: 

I confirmed that zero bootstrap crashes after `knife rehash`.
I'll add require lines to some file.

**Comment by sawanoboly** [comment] 2015-11-24 02:44
`zero bootstrap` and `zero converge` works correctly after `knife rehash` at knife-zero v1.10.1. @epcim
Please check and close it if OK.

**Comment by epcim** [comment] 2015-11-24 10:45
A pleasure to confirm, it works! Thanks.

**Comment by stevendanna** [comment] 2015-11-24 12:43
@sawanoboly Thanks for the quick turn around!

**Comment by sawanoboly** [comment] 2015-11-24 13:25
:+1:

**Closed by sawanoboly** 2015-11-24 13:25 UTC
